CREATE DATABASE IF NOT EXISTS epsilon;
USE epsilon;

GRANT SELECT,INSERT,UPDATE,DELETE ON epsilon.* TO 'epsilon'@'%' IDENTIFIED BY 'epsilon';
GRANT SELECT,INSERT,UPDATE,DELETE ON epsilon.* TO 'epsilon'@'localhost' IDENTIFIED BY 'epsilon';

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT
(
  AUDIT_DATE     TIMESTAMP                           DEFAULT CURRENT_TIMESTAMP ,
  AUDIT_CHANNEL  VARCHAR(256),
  AUDIT_MESSAGE  VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_OPERATIONS
(
  OPER_ID    INT(8)                          NOT NULL,
  OPERATION  VARCHAR(255)                      NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_OPERATIONS ADD (
  CONSTRAINT PK_AUDIT_OPERATIONS
 PRIMARY KEY
 (OPER_ID));

CREATE UNIQUE INDEX PK_AUDIT_OPERATIONS ON PKI_VA_AUDIT_OPERATIONS
(OPER_ID);

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_ENTRIES
(
  ENTRY_ID   INT(8)                          NOT NULL,
  OPER_ID    INT(8)                          NOT NULL,
  OPER_DATE  DATETIME                               NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_ENTRIES ADD (
  CONSTRAINT PK_AUDIT_ENTRIES
 PRIMARY KEY
 (ENTRY_ID));
 
ALTER TABLE PKI_VA_AUDIT_ENTRIES MODIFY ENTRY_ID   INT(8) NOT NULL AUTO_INCREMENT;

 
CREATE UNIQUE INDEX PK_AUDIT_ENTRIES ON PKI_VA_AUDIT_ENTRIES
(ENTRY_ID);

ALTER TABLE PKI_VA_AUDIT_ENTRIES ADD (
  CONSTRAINT FK_ENTRIES_OPERATIONS 
 FOREIGN KEY (OPER_ID) 
 REFERENCES PKI_VA_AUDIT_OPERATIONS (OPER_ID));

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_KEYS
(
  KEY_ID      INT(8)                         NOT NULL,
  KEY_NAME    VARCHAR(255)                     NOT NULL,
  VALUE_TYPE  INT(2)                         DEFAULT 0                     NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_KEYS ADD (
  CONSTRAINT PK_AUDIT_KEYS
 PRIMARY KEY
 (KEY_ID));
 
CREATE UNIQUE INDEX PK_AUDIT_KEYS ON PKI_VA_AUDIT_KEYS
(KEY_ID);

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_OPERS_REQ_KEYS
(
  OPER_ID         INT(8)                     NOT NULL,
  REQUEST_KEY_ID  INT(8)                     NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_OPERS_REQ_KEYS ADD (
  CONSTRAINT PK_AUDIT_OPERS_REQUEST_KEYS
 PRIMARY KEY
 (OPER_ID, REQUEST_KEY_ID));
 
CREATE UNIQUE INDEX PK_AUDIT_OPERS_REQUEST_KEYS ON PKI_VA_AUDIT_OPERS_REQ_KEYS
(OPER_ID, REQUEST_KEY_ID);

ALTER TABLE PKI_VA_AUDIT_OPERS_REQ_KEYS ADD (
  CONSTRAINT FK_OPERS_REQ_KEYS_KEYS 
 FOREIGN KEY (REQUEST_KEY_ID) 
 REFERENCES PKI_VA_AUDIT_KEYS (KEY_ID),
  CONSTRAINT FK_OPERS_REQ_KEYS_OPERATIONS 
 FOREIGN KEY (OPER_ID) 
 REFERENCES PKI_VA_AUDIT_OPERATIONS (OPER_ID));


CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_OPERS_RESP_KEYS
(
  OPER_ID          INT(8)                    NOT NULL,
  RESPONSE_KEY_ID  INT(8)                    NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_OPERS_RESP_KEYS ADD (
  CONSTRAINT PK_AUDIT_OPERS_RESPONSE_KEYS
 PRIMARY KEY
 (OPER_ID, RESPONSE_KEY_ID));

CREATE UNIQUE INDEX PK_AUDIT_OPERS_RESPONSE_KEYS ON PKI_VA_AUDIT_OPERS_RESP_KEYS
(OPER_ID, RESPONSE_KEY_ID);

ALTER TABLE PKI_VA_AUDIT_OPERS_RESP_KEYS ADD (
  CONSTRAINT FK_OPERS_RES_KEYS_KEYS 
 FOREIGN KEY (RESPONSE_KEY_ID) 
 REFERENCES PKI_VA_AUDIT_KEYS (KEY_ID),
  CONSTRAINT FK_OPERS_RES_KEYS_OPERATIONS 
 FOREIGN KEY (OPER_ID) 
 REFERENCES PKI_VA_AUDIT_OPERATIONS (OPER_ID));

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_REQUEST
(
  ENTRY_ID  INT(8)                           NOT NULL,
  KEY_ID    INT(8)                           NOT NULL,
  VC_VALUE  VARCHAR(4000),
  BO_VALUE  BLOB
);

ALTER TABLE PKI_VA_AUDIT_REQUEST ADD (
  CONSTRAINT PK_AUDIT_REQUEST
 PRIMARY KEY
 (ENTRY_ID, KEY_ID));

CREATE UNIQUE INDEX PK_AUDIT_REQUEST ON PKI_VA_AUDIT_REQUEST
(ENTRY_ID, KEY_ID);

ALTER TABLE PKI_VA_AUDIT_REQUEST ADD (
  CONSTRAINT FK_REQUEST_ENTRIES 
 FOREIGN KEY (ENTRY_ID) 
 REFERENCES PKI_VA_AUDIT_ENTRIES (ENTRY_ID),
  CONSTRAINT FK_REQUEST_KEYS 
 FOREIGN KEY (KEY_ID) 
 REFERENCES PKI_VA_AUDIT_KEYS (KEY_ID));

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_RESPONSE
(
  ENTRY_ID  INT(8)                           NOT NULL,
  KEY_ID    INT(8)                           NOT NULL,
  VC_VALUE  VARCHAR(4000),
  BO_VALUE  BLOB
);

ALTER TABLE PKI_VA_AUDIT_RESPONSE ADD (
  CONSTRAINT PK_AUDIT_RESPONSE
 PRIMARY KEY
 (ENTRY_ID, KEY_ID));
 
CREATE UNIQUE INDEX PK_AUDIT_RESPONSE ON PKI_VA_AUDIT_RESPONSE
(ENTRY_ID, KEY_ID);

ALTER TABLE PKI_VA_AUDIT_RESPONSE ADD (
  CONSTRAINT FK_RESPONSE_ENTRIES 
 FOREIGN KEY (ENTRY_ID) 
 REFERENCES PKI_VA_AUDIT_ENTRIES (ENTRY_ID),
  CONSTRAINT FK_RESPONSE_KEYS 
 FOREIGN KEY (KEY_ID) 
 REFERENCES PKI_VA_AUDIT_KEYS (KEY_ID));

CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_STATES
(
  STATE_ID  INT(8)                           NOT NULL,
  STATE     VARCHAR(255)                       NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_STATES ADD (
  CONSTRAINT PK_AUDIT_STATES
 PRIMARY KEY
 (STATE_ID));
 
CREATE UNIQUE INDEX PK_AUDIT_STATES ON PKI_VA_AUDIT_STATES
(STATE_ID);


CREATE TABLE IF NOT EXISTS PKI_VA_AUDIT_VAL_CHANNELS
(
  VC_ID  INT(8)                              NOT NULL,
  VC     VARCHAR(255)                          NOT NULL
);

ALTER TABLE PKI_VA_AUDIT_VAL_CHANNELS ADD (
  CONSTRAINT PK_AUDIT_VAL_CHANNELS
 PRIMARY KEY
 (VC_ID));

CREATE UNIQUE INDEX PK_AUDIT_VAL_CHANNELS ON PKI_VA_AUDIT_VAL_CHANNELS
(VC_ID);

CREATE TABLE IF NOT EXISTS PKI_VA_TRUSTSTORE
(
  BASE            VARCHAR(255)                 NOT NULL,
  QUALIFIER       VARCHAR(255),
  PRINCIPAL       VARCHAR(255)                 NOT NULL,
  CREDENTIALS     VARCHAR(255)                 NOT NULL,
  CREDENTIALTYPE  VARCHAR(100),
  DPTYPE          VARCHAR(100)
);

INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
1, 'CERT_ISSUER', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
2, 'CERT_SUBJECT', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
3, 'CERT_SERIAL_NUMBER', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
4, 'CERT_FINGERPRINT', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
5, 'POLICIES', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
6, 'VALIDATION_CHANNEL', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
7, 'VALIDATION_STATE', 1); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
8, 'REVOCATION_OBJECT', 2); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
9, 'POLICY_TREE', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
10, 'TRUST_ANCHOR_SUBJECT', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
11, 'TRUST_ANCHOR_SERIAL_NUMBER', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
12, 'TRUST_ANCHOR_FINGERPRINT', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
13, 'DATA_EXTRACTION_PATH', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
14, 'DATA_EXTRACTION_ITEM', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
15, 'URL', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
16, 'CRL', 2); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
17, 'SUCCESS', 3); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
99, 'INTERNAL_ERROR', 0); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
20, 'DIGEST', 2); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
19, 'CONTENT', 2); 
INSERT INTO PKI_VA_AUDIT_KEYS ( KEY_ID, KEY_NAME, VALUE_TYPE ) VALUES ( 
18, 'PKCS7', 2); 

INSERT INTO PKI_VA_AUDIT_OPERATIONS ( OPER_ID, OPERATION ) VALUES ( 
1, 'CERTIFICATE_VALIDATION'); 
INSERT INTO PKI_VA_AUDIT_OPERATIONS ( OPER_ID, OPERATION ) VALUES ( 
2, 'CERTIFICATE_DATA_EXTRACTION'); 
INSERT INTO PKI_VA_AUDIT_OPERATIONS ( OPER_ID, OPERATION ) VALUES ( 
3, 'CRL_INSTALL'); 
INSERT INTO PKI_VA_AUDIT_OPERATIONS ( OPER_ID, OPERATION ) VALUES ( 
4, 'LDAP_LOAD'); 
INSERT INTO PKI_VA_AUDIT_OPERATIONS ( OPER_ID, OPERATION ) VALUES ( 
5, 'SIGNATURE_VALIDATION'); 


INSERT INTO PKI_VA_AUDIT_STATES ( STATE_ID, STATE ) VALUES ( 
1, 'OK'); 
INSERT INTO PKI_VA_AUDIT_STATES ( STATE_ID, STATE ) VALUES ( 
2, 'REVOKED'); 
INSERT INTO PKI_VA_AUDIT_STATES ( STATE_ID, STATE ) VALUES ( 
3, 'UNKNOWN'); 

INSERT INTO PKI_VA_AUDIT_VAL_CHANNELS ( VC_ID, VC ) VALUES ( 
1, 'CRL'); 
INSERT INTO PKI_VA_AUDIT_VAL_CHANNELS ( VC_ID, VC ) VALUES ( 
2, 'OCSP'); 

commit;